<?php
$icons[1]="cog"; //Configuración
$icons[2]="folder-open-o"; //Catalogos Generales
$icons[3]="archive"; //Inventarios
$icons[4]="money"; //Ventas
$icons[5]="table"; //Reportes
$icons[6]="file"; //Administración de Ventas
$icons[7]="money"; //Gestión de Ventas
$icons[10]="cog"; //Operaciones
$icons[11]="shopping-cart"; //Compras
$icons[12]="ban"; //Administración viejo
$icons[13]="file"; //Administración
$icons[14]="line-chart"; //Reportes (PDV)
$icons[15]="calendar-check-o"; //Agenda
$icons[16]="bars"; //MRP
$icons[18]="calculator"; //Acontia
$icons[19]="file-code-o"; //Facturación
$icons[20]="square-o"; //Prueba
$icons[21]="square-o"; //test
$icons[22]="cogs"; //Producción
$icons[1018]="comment"; //SMS
$icons[1019]="truck"; //Transportes
$icons[1020]="tasks"; //SCRUMLOG
$icons[1021]="truck"; //Reportes TRT
$icons[1022]="file"; //Admin
$icons[1023]="folder-open-o"; //Catalogos
$icons[1024]="shopping-cart"; //Punto de Venta
$icons[1025]="line-chart"; //Reportes Graficos Ventas
$icons[1026]="cutlery"; //Foodware
$icons[1028]="money"; //Hazbizne
$icons[1030]="building"; //Construccion_viejo
$icons[1031]="laptop"; //Netwarmonitor
$icons[1032]="building"; //Xtructur
$icons[1033]="usd"; //Bancos
$icons[1034]="star"; //Eventos
$icons[1035]="shopping-bag"; //Netwarstore Admin
$icons[1036]="file-text-o"; //Pedidos y Cotizaciones
$icons[1037]="bank"; //Inadem
$icons[1042]="shopping-basket"; //Punto de venta
$icons[1043]="file-code-o"; //Facturacion
$icons[1044]="shopping-cart"; //Compras
$icons[1045]="money"; //Ventas
$icons[1046]="archive"; //Inventario
$icons[1047]="file"; //Administracion
$icons[1048]="folder-open-o"; //Catalogos
$icons[1049]="line-chart"; //Reportes
$icons[1050]="cog"; //Configuracion
$icons[1051]="cutlery"; //Servicios(Foodware)
$icons[1052]="calendar"; //Reservaciones(Foodware)
$icons[1053]="list-alt"; //Recetas(Foodware)
$icons[1054]="balance-scale";//conciliacion
$icons[1055]="street-view";//Nominas
$icons[1056]="info";//Inovekia
$icons[1057]="line-chart";//Reportes
$icons[1058]="wrench"; //Conciliacion Bancaria
$icons[1059]="random";//Carga/Configuración de Obra
$icons[1060]="Building";//Administración de Obra
$icons[1062]="upload";//Presupuesto xtrc
$icons[1063]="list-alt";//Perfil de empleados xtrc
$icons[1064]="user-plus";//Altas de sistema xtrc
$icons[1065]="shopping-cart";//Compras xtrc
$icons[1066]="cubes";//inventarios xtrc
$icons[1067]="history";//control de obra xtrc
$icons[1068]="user";//personal xtrc
$icons[1069]="building";//control de estimaciones xtrc
$icons[1070]="repeat";//presupuesto actualizado xtrc
$icons[1071]="money";//administracion financiera xtrc
$icons[1072]="industry";//Proceso de Producción
$icons[1061]="building";//Activos Fijos
$icons[1073]="money";//Cotizaciones
$icons[1040]="truck";//Transporte
?>
